### ISSUE TITLE
Cascading class load in MixinPlugin

### ISSUE THREAD

**Issue by crosby-moe** [crazysmc/thorough-keybindings#5]
This mod's mixin plugin (`io.github.crazysmc.thrkbs.core`) causes a cascading class load both by loading `io.github.crazysmc.thrkbs.core.MappingRegistry` which references the vanilla class `net.minecraft.client.KeyMapping`, and by getting the static field `MAPPING_REGISTRY` from `io.github.crazysmc.thrkbs.core.ThoroughKeybindings` which causes static class initialization and loads several other classes via `ServiceLoader`.

This results in several Minecraft classes being loaded early which causes the game to crash with a `MixinTargetAlreadyLoadedException` whenever another mod tries to mixin into these classes. For example, this mod loads `net.minecraft.network.chat.Component` early making it impossible to mixin into.

It would be ideal to move the parts of `MappingRegistry` that are used in the mixin plugin in a separate class in order to maximize compatibility with other mods.

**Comment by crazysmc** [comment]
Moving the ownership of the `MappingRegistry` instance is a good idea. The mixin plugin really should not load all the rest of `ThoroughKeybindings` static fields.

Do you know a mod that causes this error? All the other mods I use seem to have no relevant mixin overlap, so I did not notice this earlier.

Edit: Even if I cannot test the error right now, it should be fixed in the next update.
